# Generated by Django 5.1.4 on 2026-04-19 21:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='age_restriction',
            field=models.CharField(blank=True, choices=[('', 'No restriction'), ('18+', '18+'), ('21+', '21+')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='event',
            name='incognito_fee_cents',
            field=models.PositiveIntegerField(default=0, help_text='Extra fee in cents for hiding attendee name from public grid'),
        ),
        migrations.AddField(
            model_name='event',
            name='max_capacity',
            field=models.PositiveIntegerField(blank=True, help_text='Total attendees allowed', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='public_attendee_list',
            field=models.BooleanField(default=True, help_text='Non-hosts can see the attendee directory'),
        ),
        migrations.AddField(
            model_name='event',
            name='ticketing_enabled',
            field=models.BooleanField(default=False, help_text='Paid tickets required (vs free RSVP)'),
        ),
        migrations.CreateModel(
            name='EventRSVP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('going', 'Going'), ('maybe', 'Maybe'), ('interested', 'Interested'), ('not_going', 'Not going')], default='going', max_length=15)),
                ('incognito', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rsvps', to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rsvps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['event', 'status'], name='events_even_event_i_c5a858_idx'), models.Index(fields=['user', '-created_at'], name='events_even_user_id_9d1575_idx')],
                'unique_together': {('event', 'user')},
            },
        ),
    ]
