# Generated by Django 5.1.4 on 2026-04-21 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0002_booking_booking_type_booking_payment_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HandoverReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moment', models.CharField(choices=[('delivery', 'Delivery'), ('return', 'Return')], max_length=20)),
                ('photo_urls', models.JSONField(blank=True, default=list)),
                ('gps_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('gps_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('owner_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('renter_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('owner_sms_code', models.CharField(blank=True, default='', max_length=10)),
                ('renter_sms_code', models.CharField(blank=True, default='', max_length=10)),
                ('owner_sms_verified', models.BooleanField(default=False)),
                ('renter_sms_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handover_receipts', to='bookings.booking')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
