# Generated by Django 5.1.4 on 2026-04-14 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venueprofile',
            name='bike_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='venueprofile',
            name='nearby_transit',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='venueprofile',
            name='parking_info',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='venueprofile',
            name='transit_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='venueprofile',
            name='walkability_score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
