# Generated by Django 5.1.4 on 2026-04-18 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_emailverificationtoken_passwordresettoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('venue', 'Venue'), ('creator', 'Creator'), ('audience', 'Audience')], max_length=10),
        ),
        migrations.CreateModel(
            name='AudienceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=255)),
                ('bio', models.TextField(blank=True, default='')),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('country', models.CharField(default='US', max_length=100)),
                ('cover_image', models.URLField(blank=True, default='')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('interests', models.JSONField(blank=True, default=list)),
                ('socials', models.JSONField(blank=True, default=dict)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='audience_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
