# Generated by Django 5.1.4 on 2026-04-21 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_pushsubscription_and_more'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='care_score',
            field=models.FloatField(default=5.0),
        ),
        migrations.AddField(
            model_name='user',
            name='display_mode',
            field=models.CharField(choices=[('real', 'Real name'), ('pseudo', 'Pseudonym'), ('anonymous', 'Anonymous')], default='real', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='is_kyc_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_private_circle',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='marketplace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='core.marketplace'),
        ),
        migrations.AddField(
            model_name='user',
            name='pseudonym',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='user',
            name='stripe_account_id',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='user',
            name='stripe_customer_id',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
