# Generated by Django 5.1.4 on 2026-04-21 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_care_score_user_display_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_physical_shop',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_pro',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='pro_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='pro_tier',
            field=models.CharField(choices=[('none', 'Particulier'), ('negafa', 'Négafa indépendante'), ('atelier', 'Atelier / Créatrice pro'), ('boutique', 'Boutique physique'), ('partner', 'Partenaire officiel')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='shop_address',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='user',
            name='shop_city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='shop_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='vat_number',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
