# Generated by Django 5.0.6 on 2026-05-02 21:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0002_booking_booking_type_booking_payment_status_and_more'),
        ('handovers', '0001_initial'),
        ('spaces', '0006_space_available_for_rent_space_available_for_sale_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConditionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moment', models.CharField(choices=[('baseline', 'Baseline (mise en ligne)'), ('pre_shipment', 'Avant envoi'), ('reception', 'Réception cliente'), ('pre_return', 'Avant retour'), ('post_return', 'Réception loueuse'), ('manual', 'Contrôle manuel')], max_length=20)),
                ('photo_urls', models.JSONField(default=list)),
                ('video_url', models.URLField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('ai_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('ai_is_acceptable', models.BooleanField(blank=True, null=True)),
                ('ai_detected_issues', models.JSONField(blank=True, default=list)),
                ('ai_estimated_repair_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('ai_recommendation', models.CharField(blank=True, choices=[('accept', 'Accepter'), ('minor_dispute', 'Litige mineur'), ('major_dispute', 'Litige majeur'), ('inconclusive', 'Inconcluant')], default='', max_length=20)),
                ('ai_raw', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('handover', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='condition_reports', to='handovers.handoverreceipt')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condition_reports', to='spaces.space')),
                ('rental', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='condition_reports', to='bookings.booking')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='condition_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
