# Generated by Django 5.1.4 on 2026-04-14 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('spaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('technology', models.CharField(choices=[('vr', 'Virtual Reality'), ('ar', 'Augmented Reality'), ('mr', 'Mixed Reality'), ('immersive', 'Immersive Installation'), ('projection', 'Projection Mapping'), ('interactive', 'Interactive Art'), ('other', 'Other')], default='immersive', max_length=20)),
                ('year', models.PositiveIntegerField()),
                ('cover_image', models.URLField(blank=True, default='')),
                ('video_url', models.URLField(blank=True, default='')),
                ('external_url', models.URLField(blank=True, default='')),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_projects', to='accounts.creatorprofile')),
            ],
            options={
                'ordering': ['-year', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('caption', models.CharField(blank=True, default='', max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='proposals.portfolioproject')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('project_type', models.CharField(choices=[('vr', 'Virtual Reality'), ('ar', 'Augmented Reality'), ('mr', 'Mixed Reality'), ('immersive', 'Immersive Installation'), ('projection', 'Projection Mapping'), ('interactive', 'Interactive Art'), ('other', 'Other')], default='immersive', max_length=20)),
                ('proposed_start_date', models.DateField()),
                ('proposed_end_date', models.DateField()),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('technical_requirements', models.TextField(blank=True, default='')),
                ('audience_description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='draft', max_length=20)),
                ('venue_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='accounts.creatorprofile')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='spaces.space')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
