# Generated by Django 5.1.4 on 2026-04-17 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioproject',
            name='cover_image',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='portfolioproject',
            name='video_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
