# Generated by Django 5.1.4 on 2026-04-17 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0002_alter_portfolioproject_cover_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioproject',
            name='external_links',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='portfolioproject',
            name='gallery_images',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='portfolioproject',
            name='videos',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
