# Generated by Django 5.1.4 on 2026-04-21 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marketplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('domain', models.CharField(blank=True, default='', max_length=255)),
                ('primary_language', models.CharField(default='fr', max_length=10)),
                ('secondary_language', models.CharField(blank=True, default='', max_length=10)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=15, max_digits=5)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('primary_color', models.CharField(blank=True, default='', max_length=20)),
                ('secondary_color', models.CharField(blank=True, default='', max_length=20)),
                ('logo_url', models.URLField(blank=True, default='')),
                ('tagline_key', models.CharField(blank=True, default='', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
