# Generated by Django 5.1.4 on 2026-04-21 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticketwaitlist'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='ticketwaitlist',
            new_name='tickets_tic_tier_id_344f4a_idx',
            old_name='tickets_tic_tier_id_idx',
        ),
        migrations.AlterField(
            model_name='ticketwaitlist',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
