# Generated by Django 5.1.4 on 2026-04-14 02:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField()),
                ('space_type', models.CharField(choices=[('gallery_room', 'Gallery Room'), ('main_hall', 'Main Hall'), ('outdoor', 'Outdoor Space'), ('theater', 'Theater/Auditorium'), ('lobby', 'Lobby/Foyer'), ('studio', 'Studio Space'), ('entire_venue', 'Entire Venue'), ('other', 'Other')], default='gallery_room', max_length=20)),
                ('area_sqft', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('ceiling_height_ft', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('max_capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('has_wifi', models.BooleanField(default=True)),
                ('has_power_outlets', models.BooleanField(default=True)),
                ('has_projection_surfaces', models.BooleanField(default=False)),
                ('has_sound_system', models.BooleanField(default=False)),
                ('has_blackout_capability', models.BooleanField(default=False)),
                ('has_climate_control', models.BooleanField(default=True)),
                ('technical_notes', models.TextField(blank=True, default='')),
                ('daily_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('weekly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('monthly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spaces', to='accounts.venueprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_available', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='spaces.space')),
            ],
            options={
                'verbose_name_plural': 'Availabilities',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='SpaceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('caption', models.CharField(blank=True, default='', max_length=255)),
                ('is_primary', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='spaces.space')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SavedSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_spaces', to=settings.AUTH_USER_MODEL)),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='spaces.space')),
            ],
            options={
                'unique_together': {('user', 'space')},
            },
        ),
    ]
