# Generated by Django 5.1.4 on 2026-04-14 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='features',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='space',
            name='floor_plan_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='SpaceAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file_url', models.URLField()),
                ('file_type', models.CharField(choices=[('floor_plan', 'Floor Plan'), ('spec_sheet', 'Spec Sheet'), ('brochure', 'Brochure'), ('contract', 'Contract Template'), ('other', 'Other')], default='other', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='spaces.space')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
