# Generated by Django 5.1.4 on 2026-04-14 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0002_space_features_space_floor_plan_url_spaceattachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
