# Generated by Django 5.1.4 on 2026-04-15 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0003_alter_space_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='video_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
