# Generated by Django 5.1.4 on 2026-04-17 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0004_space_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='video_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='spaceimage',
            name='image_url',
            field=models.TextField(),
        ),
    ]
