# Generated by Django 5.1.4 on 2026-04-21 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('spaces', '0005_alter_space_video_url_alter_spaceimage_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='available_for_rent',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='space',
            name='available_for_sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='space',
            name='brand',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='space',
            name='category',
            field=models.CharField(blank=True, choices=[('caftan', 'Caftan'), ('takchita', 'Takchita'), ('jabador', 'Jabador'), ('jellaba', 'Jellaba'), ('gandoura', 'Gandoura'), ('accessoire', 'Accessoire')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='space',
            name='color',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='space',
            name='deposit_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='space',
            name='marketplace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spaces', to='core.marketplace'),
        ),
        migrations.AddField(
            model_name='space',
            name='occasion_tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='space',
            name='qr_code',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='space',
            name='rental_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='space',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='space',
            name='size',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
