# Generated by Django 5.0.6 on 2026-05-03 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('community_review', 'Avis communauté'), ('p2p_listing', 'Mise en ligne particulière'), ('p2p_offer', 'Annonce — louer ma pièce'), ('pro_drop', 'Drop boutique pro'), ('pro_event', 'Évènement pro (vide-dressing, ouverture…)'), ('pro_styling', 'Conseil styling pro'), ('other', 'Autre')], default='community_review', max_length=20),
        ),
    ]
