# Generated by Django 5.0.6 on 2026-05-02 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_restructure_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='criteria',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='review',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='review',
            name='direction',
            field=models.CharField(choices=[('creator_to_venue', 'Cliente → Loueuse'), ('venue_to_creator', 'Loueuse → Cliente')], max_length=20),
        ),
    ]
